<?php
/**
 * AI Briefing Feature for Innovopedia
 * Inspired by Business Insider
 */

defined( 'ABSPATH' ) || exit;

/**
 * Register Meta Box for AI Briefing
 */
function innovopedia_register_ai_briefing_metabox() {
	add_meta_box(
		'innovopedia_ai_briefing',
		esc_html__( 'AI Briefing (Business Insider Style)', 'foxiz' ),
		'innovopedia_ai_briefing_callback',
		'post',
		'normal',
		'high'
	);
}
add_action( 'add_meta_boxes', 'innovopedia_register_ai_briefing_metabox' );

/**
 * Meta Box Callback
 */
function innovopedia_ai_briefing_callback( $post ) {
	wp_nonce_field( 'innovopedia_save_ai_briefing', 'innovopedia_ai_briefing_nonce' );

	$summary = get_post_meta( $post->ID, '_innovopedia_ai_summary', true );
	$bullets = get_post_meta( $post->ID, '_innovopedia_ai_bullets', true );
	$audio_url = get_post_meta( $post->ID, '_innovopedia_ai_audio_url', true );

	echo '<div class="innovopedia-meta-field">';
	echo '<label for="innovopedia_ai_summary"><strong>' . esc_html__( 'Brief Summary', 'foxiz' ) . '</strong></label>';
	echo '<textarea id="innovopedia_ai_summary" name="innovopedia_ai_summary" rows="3" style="width:100%; margin-bottom: 15px;">' . esc_textarea( $summary ) . '</textarea>';
	echo '</div>';

	echo '<div class="innovopedia-meta-field">';
	echo '<label for="innovopedia_ai_bullets"><strong>' . esc_html__( 'Key Takeaways (One per line)', 'foxiz' ) . '</strong></label>';
	echo '<textarea id="innovopedia_ai_bullets" name="innovopedia_ai_bullets" rows="5" style="width:100%; margin-bottom: 15px;">' . esc_textarea( $bullets ) . '</textarea>';
	echo '</div>';

	echo '<div class="innovopedia-meta-field">';
	echo '<label for="innovopedia_ai_audio_url"><strong>' . esc_html__( 'AI Audio Briefing URL (Optional)', 'foxiz' ) . '</strong></label>';
	echo '<input type="text" id="innovopedia_ai_audio_url" name="innovopedia_ai_audio_url" value="' . esc_attr( $audio_url ) . '" style="width:100%;">';
	echo '</div>';

	echo '<p class="description">' . esc_html__( 'Fill this out to display a premium AI Briefing block at the top of the post.', 'foxiz' ) . '</p>';
}

/**
 * Save Meta Box Data
 */
function innovopedia_save_ai_briefing( $post_id ) {
	if ( ! isset( $_POST['innovopedia_ai_briefing_nonce'] ) || ! wp_verify_nonce( $_POST['innovopedia_ai_briefing_nonce'], 'innovopedia_save_ai_briefing' ) ) {
		return;
	}
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
		return;
	}
	if ( ! current_user_can( 'edit_post', $post_id ) ) {
		return;
	}

	if ( isset( $_POST['innovopedia_ai_summary'] ) ) {
		update_post_meta( $post_id, '_innovopedia_ai_summary', sanitize_textarea_field( $_POST['innovopedia_ai_summary'] ) );
	}
	if ( isset( $_POST['innovopedia_ai_bullets'] ) ) {
		update_post_meta( $post_id, '_innovopedia_ai_bullets', sanitize_textarea_field( $_POST['innovopedia_ai_bullets'] ) );
	}
	if ( isset( $_POST['innovopedia_ai_audio_url'] ) ) {
		update_post_meta( $post_id, '_innovopedia_ai_audio_url', esc_url_raw( $_POST['innovopedia_ai_audio_url'] ) );
	}
}
add_action( 'save_post', 'innovopedia_save_ai_briefing' );

/**
 * Render AI Briefing on Frontend
 */
function innovopedia_render_ai_briefing( $content ) {
	if ( ! is_singular( 'post' ) || ! is_main_query() ) {
		return $content;
	}

	$post_id = get_the_ID();
	$summary = get_post_meta( $post_id, '_innovopedia_ai_summary', true );
	$bullets = get_post_meta( $post_id, '_innovopedia_ai_bullets', true );
	$audio_url = get_post_meta( $post_id, '_innovopedia_ai_audio_url', true );

	if ( empty( $summary ) && empty( $bullets ) ) {
		return $content;
	}

	$bullet_points = explode( "\n", $bullets );
	$bullet_points = array_filter( array_map( 'trim', $bullet_points ) );

	ob_start();
	?>
	<div class="innovopedia-briefing-wrap">
		<div class="briefing-header">
			<span class="briefing-label"><i class="rbi rbi-lightning"></i> <?php esc_html_e( 'AI BRIEFING', 'foxiz' ); ?></span>
			<?php if ( ! empty( $audio_url ) ) : ?>
				<div class="briefing-audio">
					<audio controls>
						<source src="<?php echo esc_url( $audio_url ); ?>" type="audio/mpeg">
						<?php esc_html_e( 'Your browser does not support the audio element.', 'foxiz' ); ?>
					</audio>
				</div>
			<?php endif; ?>
		</div>
		<div class="briefing-content">
			<?php if ( ! empty( $summary ) ) : ?>
				<p class="briefing-summary"><?php echo esc_html( $summary ); ?></p>
			<?php endif; ?>
			<?php if ( ! empty( $bullet_points ) ) : ?>
				<ul class="briefing-bullets">
					<?php foreach ( $bullet_points as $point ) : ?>
						<li><?php echo esc_html( $point ); ?></li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		</div>
		<div class="briefing-footer">
			<span class="briefing-disclaimer"><?php esc_html_e( 'Generated by Innovopedia AI • Verified by Editors', 'foxiz' ); ?></span>
		</div>
	</div>
	<?php
	$briefing_html = ob_get_clean();

	return $briefing_html . $content;
}
add_filter( 'the_content', 'innovopedia_render_ai_briefing', 5 );
/**
 * --- INNOVOPEDIA AI SETTINGS & AJAX ---
 */

/**
 * Add AI Settings Page
 */
function innovopedia_ai_settings_page() {
	add_options_page(
		'Innovopedia AI Settings',
		'AI Briefing',
		'manage_options',
		'innovopedia-ai-settings',
		'innovopedia_ai_settings_callback'
	);
}
add_action( 'admin_menu', 'innovopedia_ai_settings_page' );

function innovopedia_ai_settings_callback() {
	?>
	<div class="wrap">
		<h1>Innovopedia AI Settings</h1>
		<form method="post" action="options.php">
			<?php
			settings_fields( 'innovopedia_ai_group' );
			do_settings_sections( 'innovopedia-ai-settings' );
			submit_button();
			?>
		</form>
	</div>
	<?php
}

function innovopedia_register_settings() {
	register_setting( 'innovopedia_ai_group', 'innovopedia_openrouter_api_key' );
	register_setting( 'innovopedia_ai_group', 'innovopedia_ai_model', ['default' => 'mistralai/mistral-7b-instruct:free'] );

	add_settings_section( 'innovopedia_ai_main', 'API Configuration', null, 'innovopedia-ai-settings' );

	add_settings_field( 'openrouter_api_key', 'OpenRouter API Key', function() {
		$value = get_option( 'innovopedia_openrouter_api_key' );
		echo '<input type="password" name="innovopedia_openrouter_api_key" value="' . esc_attr( $value ) . '" class="regular-text">';
	}, 'innovopedia-ai-settings', 'innovopedia_ai_main' );

	add_settings_field( 'ai_model', 'AI Model ID', function() {
		$value = get_option( 'innovopedia_ai_model', 'mistralai/mistral-7b-instruct:free' );
		echo '<input type="text" name="innovopedia_ai_model" value="' . esc_attr( $value ) . '" class="regular-text">';
		echo '<p class="description">Use "mistralai/mistral-7b-instruct:free" for zero cost.</p>';
	}, 'innovopedia-ai-settings', 'innovopedia_ai_main' );
}
add_action( 'admin_init', 'innovopedia_register_settings' );

/**
 * AJAX Handler to Fetch Briefing
 */
function innovopedia_get_briefing_ajax() {
	check_ajax_referer( 'briefing_nonce', 'nonce' );

	$stories = [];
	$posts = get_posts([
		'numberposts' => 5,
		'post_status'  => 'publish'
	]);

	$api_key = get_option( 'innovopedia_openrouter_api_key' );
	$model = get_option( 'innovopedia_ai_model', 'mistralai/mistral-7b-instruct:free' );

	foreach ( $posts as $post ) {
		$summary = get_post_meta( $post->ID, '_innovopedia_ai_summary', true );
		
		// If no summary exists, try to generate one (optional, could be slow in AJAX)
		if ( empty( $summary ) && ! empty( $api_key ) ) {
			$summary = innovopedia_generate_ai_summary( $post->post_content );
			update_post_meta( $post->ID, '_innovopedia_ai_summary', $summary );
		}

		$stories[] = [
			'title'   => get_the_title( $post->ID ),
			'summary' => ! empty( $summary ) ? $summary : wp_trim_words( $post->post_content, 30 ),
			'image'   => get_the_post_thumbnail_url( $post->ID, 'medium_large' ),
			'link'    => get_permalink( $post->ID )
		];
	}

	wp_send_json_success( ['stories' => $stories] );
}
add_action( 'wp_ajax_innovopedia_get_briefing', 'innovopedia_get_briefing_ajax' );
add_action( 'wp_ajax_nopriv_innovopedia_get_briefing', 'innovopedia_get_briefing_ajax' );

/**
 * Call OpenRouter API to generate summary
 */
function innovopedia_generate_ai_summary( $content ) {
	$api_key = get_option( 'innovopedia_openrouter_api_key' );
	$model = get_option( 'innovopedia_ai_model', 'mistralai/mistral-7b-instruct:free' );

	if ( empty( $api_key ) ) return '';

	$response = wp_remote_post( 'https://openrouter.ai/api/v1/chat/completions', [
		'headers' => [
			'Authorization' => 'Bearer ' . $api_key,
			'Content-Type'  => 'application/json',
			'HTTP-Referer'  => home_url(),
		],
		'body' => json_encode([
			'model' => $model,
			'messages' => [
				['role' => 'system', 'content' => 'You are a premium news editor for Innovopedia. Summarize the following news article into 2-3 engaging sentences for a quick briefing.'],
				['role' => 'user', 'content' => wp_strip_all_tags( $content )]
			]
		]),
		'timeout' => 30
	]);

	if ( is_wp_error( $response ) ) return '';

	$body = json_decode( wp_remote_retrieve_body( $response ), true );
	return isset( $body['choices'][0]['message']['content'] ) ? $body['choices'][0]['message']['content'] : '';
}

/**
 * --- INNOVOPEDIA GLOBAL BRIEFING SIDEBAR HTML ---
 */

/**
 * Add Briefing Sidebar to Footer
 */
function innovopedia_briefing_sidebar_html() {
	?>
	<div id="innovopedia-briefing-sidebar" class="briefing-sidebar">
		<div class="briefing-sidebar-inner">
			<div class="sidebar-header">
				<div class="header-left">
					<span class="sidebar-logo-icon">|||</span>
					<h2 class="sidebar-title"><?php esc_html_e( 'Your Briefing', 'foxiz' ); ?></h2>
					<span class="ai-generated-badge"><?php esc_html_e( 'AI GENERATED', 'foxiz' ); ?> <i class="rbi rbi-info"></i></span>
				</div>
				<button id="close-briefing" class="close-btn">&times;</button>
			</div>
			
			<div id="briefing-loader" class="briefing-loader" style="display:none; text-align:center; padding: 50px;">
				<div class="rb-loader"></div>
				<p><?php esc_html_e( 'Preparing your briefing...', 'foxiz' ); ?></p>
			</div>

			<div id="briefing-stories-container" class="briefing-stories">
				<!-- Stories will be loaded here via AJAX -->
			</div>

			<div class="sidebar-footer">
				<div class="audio-controls">
					<button id="play-pause-briefing" class="play-btn"><i class="rbi rbi-play"></i></button>
					<div id="briefing-progress-segments" class="progress-segments">
						<!-- Progress bars for each story -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="briefing-overlay" class="briefing-overlay"></div>
	<?php
}
add_action( 'wp_footer', 'innovopedia_briefing_sidebar_html' );

/**
 * --- INNOVOPEDIA BRIEFING TRIGGER SHORTCODE ---
 * Use: [innovopedia_briefing]
 */
function innovopedia_briefing_shortcode( $atts ) {
	$atts = shortcode_atts( [
		'greeting' => 'yes',
		'label'    => 'Your Briefing',
	], $atts );

	$time = current_time( 'G' );
	$greeting_text = '';

	if ( 'yes' === $atts['greeting'] ) {
		if ( $time >= 5 && $time < 12 ) {
			$greeting_text = esc_html__( 'Good morning!', 'foxiz' );
		} elseif ( $time >= 12 && $time < 18 ) {
			$greeting_text = esc_html__( 'Good afternoon!', 'foxiz' );
		} else {
			$greeting_text = esc_html__( 'Good evening!', 'foxiz' );
		}
	}

	ob_start();
	?>
	<div class="innovopedia-briefing-trigger-wrap">
		<?php if ( ! empty( $greeting_text ) ) : ?>
			<span class="briefing-greeting"><?php echo $greeting_text; ?></span>
		<?php endif; ?>
		<a href="#" class="your-briefing-trigger briefing-badge">
			<span class="badge-icon"><i class="rbi rbi-play"></i></span>
			<span class="badge-text"><?php echo esc_html( $atts['label'] ); ?></span>
		</a>
	</div>
	<?php
	return ob_get_clean();
}
add_shortcode( 'innovopedia_briefing', 'innovopedia_briefing_shortcode' );

/**
 * Enqueue Sidebar Scripts and Styles
 */
function innovopedia_enqueue_briefing_assets() {
	wp_enqueue_style( 'innovopedia-briefing-css', get_template_directory_uri() . '/assets/css/briefing-sidebar.css', [], '1.0.0' );
	wp_enqueue_script( 'innovopedia-briefing-js', get_template_directory_uri() . '/assets/js/briefing-sidebar.js', ['jquery'], '1.0.0', true );
	
	wp_localize_script( 'innovopedia-briefing-js', 'innovopediaBriefing', [
		'ajax_url' => admin_url( 'admin-ajax.php' ),
		'nonce'    => wp_create_nonce( 'briefing_nonce' )
	]);
}
add_action( 'wp_enqueue_scripts', 'innovopedia_enqueue_briefing_assets' );
